### PR TITLE
Fix for VNETEE-278 and 186317.

### PR DESCRIPTION
**Pull request by koteswar16**
Removed unwanted error log in helper method.
Made ip_address in "bnp_physical_switches" as unique key to avoid warning message.

### CODE REVIEW

**Comment by hp-networking** [comment]
my initial review comments,

1. please remove the relevant helper method update_bnp_phys_swport_status from DB and the unit test cases.
2.get_all_bnp_swport_mappings - no more it is required also from unit test cases. 
3. please remove the configuration parameters from ml2_conf_hp.ini.

**Comment by koteswar16** [comment]
1. update_bnp_phys_swport_status is used in _update_switch_ports() also.
2. get_all_bnp_swport_mappings is also used in bind_port_to_segment() but commented. In future you may use it.

**Comment by selvakumars2** [comment]
Thanks.. how about handling for switch not reachable during show command.
the port_status should be unknown.

**Comment by hp-networking** [comment]
Looks good.

**Pull request merged**
