### PR TITLE
Switch Update REST API Implementation

### PR DESCRIPTION
**Pull request by neethi-shashidhar**

### CODE REVIEW

**Comment by SyedAhmedMohiuddinPeerzade** [comment]
Line # 225 - no need to maintain update_list
Line # 229,230 - no required, as db.get_bnp_phys_switch(context, id) gives only one record or None
Line # 243 - change the name of the variable, it can be something like 'port_prov_status'
Line # 273 - instead of 'and not' xor operator can be used and code from line # 281-288 can be removed
Line # 332 - 334 - No need to call db update method multiple times, just have one dict and update once

**Comment by SyedAhmedMohiuddinPeerzade** [comment]
In bnp_switch.py file
    Line # 274 -to 280 - not required, we can do something like:
               if body['management_protocol'] != switch['management_protocol']
                           raise Exception
    Line # 273 and 281 - Instead of 'if' ,  'elif' should be used.

**Comment by SyedAhmedMohiuddinPeerzade** [comment]
In bnp_credential.py
    Line # 125 to 132 - Instead of fetching all the switches, we can make a db query something like 'is exist' to 'bnp_physical_switches' with credentials id as filter.

**Comment by koteswar16** [comment]
/ml2/extensions/bnp_switch.py
L243: you can avoid temp variable 'name'
if body.get('name'):
 +            switch['name'] = body['name']
 
L247: you can avoid temp var 'vendor'
L249: is this 'if' condition required here?
L253: _get_access_param returns a value and you are not storing it anywhere?
L269: same as above

**Comment by neethi-shashidhar** [comment]
/ml2/extensions/bnp_switch.py
L253 and L269 : _get_access_param is being used as a validator method here for management protocol and crdentials. i do not require the value returned by the method.

**Pull request merged**
