### PR TITLE
Credential REST API's for DELETE/LIST/SHOW

### PR DESCRIPTION
**Pull request by manju754**
1. added support for Credential REST API's for DELETE/LIST/SHOW commands
2. multiple names are allowed
3. keypath issue addressed in netconf
4. appending 's' or  'n' to uuid in credential create is removed.
5. changded db schema for uuid back to 36 characters.

### CODE REVIEW

**Comment by koteswar16** [comment]
my comments:
L562 and L575: doc strings are misleading.

**Comment by hp-networking** [comment]
Looks ok  except the docstring that Koteswar has mentiond. could you please address this?

**Comment by manju754** [comment]
Doc strings are already addressed in the previous patch itself.

**Comment by hp-networking** [comment]
Hi Manju,
what I mentioned was at the below lines,
1. def get_**snmp**_cred_by_id(context, id):
 @@ -585,11 +609,11 @@ def get_netconf_cred_by_name(context, name):
      """Get **NETCONF** Credential that matches name."""		      """Get NETCONF Credential that matches name."""


2. def delete_**netcon**f_cred_by_id(context, id):
 +    """Delete** snmp **credential by id."""

**Comment by manju754** [comment]
Addressed the review comments and committed code for the same.

**Pull request merged**
